### ISSUE TITLE
Make validators easier to write

### ISSUE THREAD

**Issue by yosikarl** [FIRSTIsrael/fll-scoresheet-docs#1]
Validators, as presented in the [readme.md](https://github.com/FIRSTIsrael/temporary-scoresheet-demo/blob/main/README.md) examples, are too complex for non-programmers to read or write.
See:
```
values => {
      const m06 = values.find(m => m.id === 'm06');
      const m07 = values.find(m => m.id === 'm07');
      if (m06 && m07) {
        if (m06.values[1] && m07.values[0]) throw new ScoresheetError('e1');
      }
    }
```
I suggets the following changes:

- Do not use the term `values` for two very different things.
- Provide a utility func instead of forcing the user to learn the typescript find(...) syntax.
This would end up with:
```
missions => {
      const m06 = find_mission(missions, 'm06');
      const m07 = find_mission(missions, 'm07');
      if (m06 && m07) {
        if (m06.values[1] && m07.values[0]) throw new ScoresheetError('e1');
      }
    }
```
If you make `missions` an object and not just an array, you can make the syntax even easier for users:
```
missions => {
      const m06 = missions.find('m06');
      const m07 = missions.find('m07');
      if (m06 && m07) {
        if (m06.values[1] && m07.values[0]) throw new ScoresheetError('e1');
      }
    }
```
Perhaps even (I don't know typescript well enough to tell if this is doable; In Python I could do soemthing similar):
```
missions => {
      const m06 = missions.m06;
      const m07 = missions.m07;
      if (m06 && m07) {
        if (m06.values[1] && m07.values[0]) throw new ScoresheetError('e1');
      }
    }
```
And then this can be simplified to:
```
missions => {
        if (missions.m06.values[1] && missions.m07.values[0]) throw new ScoresheetError('e1');
    }
```

**Comment by ofekashery** [comment]
@johnmeshulam Maybe provide the missions as an object?
```json
{
  "m01_1": 1,
  "m01_2": true,
  "m02_1": 4
}
```

**Comment by johnmeshulam** [comment]
Missions is an array since the number and ids of missions changes each year. Providing it as an object would mean that the DB interface would have to be changed every year making the typing not generic.

If you can get around this then we can make it an object but since this is TS and not JS it's a bit of a pain

**Comment by ofekashery** [comment]
Actually, I mean the validators API only.

Regardless, even within the array the values are stored differently, for example boolean vs number for a clause - but anyway the DB and external API are separate thing.

**Comment by johnmeshulam** [comment]
Fixed, committing to lems soon
